### ISSUE TITLE
[BUG] Doesn't Work with Floats

### ISSUE THREAD

**Issue by andresams** [markmead/alpinejs-money#5]
Hi,

I'm trying to use your plugin with the following snippet:

`<span class="account-product-price" x-money="product.price_inc_tax" data-lang="en-US" data-currency="USD"></span>`

Where product.price_inc_tax is 99.000

The output is as follows:
`$0.99`

I believe it is because it expects the input to be an integer number. Is this the intent behavior or a bug?

**Comment by markmead** [comment]
I've added a solution for this in #6
