### ISSUE TITLE
Support for dynamic locale

### ISSUE THREAD

**Issue by billybillydev** [markmead/alpinejs-money#8]
Hi there,

First, thanks a lot for this plugin !
I'm wondering if is it possible to dynamically apply locale.
For example:

<span x-money.${locale}.decimal="productPrice"></span>

If not the case, how can we make a workaround ?

Sincerelly

**Comment by markmead** [comment]
Why is this needed? I'm not sure how you've ended up in that situation, ha! 

One thing I could do is add support for a `data-locale` on the element.

**Comment by markmead** [comment]
Pushed an update to allow for data attributes, that should help.

**Comment by billybillydev** [comment]
Hi Mark, thanks for your reply. The need is to avoid doing "x-money.en-GB.GBP". I see your update about data-locale. Maybe  my question was not very clear, I apologize. The closest idea I thought was something really like "x-money.shopify", as mentionned in your doc, Shopify object has locale and currency. So is it relevant to have same behaviour for something other than shopify ?
Here is a quick concept:
`
 <div x-data="{ localeObj: { locale: 'en-GB', currency: 'GBP' }, price: 5000 }">
   <button x-on:click="localeObj = { locale: 'fr-FR', currency: 'EUR' }">Use €</button>
   <button x-on:click="localeObj = { locale: 'en-GB', currency: 'GBP' }">Use £</button>
   <span x-money.localeObj="price"></span>
 </div>
`
For whatever reason, localeObj can be mutated and the span using x-money get the update value.

Or, use the data-locale idea you suggested:
`
 <div x-data="{ localeObj: { locale: 'en-GB', currency: 'GBP' }, price: 5000 }">
   <button x-on:click="localeObj = { locale: 'fr-FR', currency: 'EUR' }">Use €</button>
   <button x-on:click="localeObj = { locale: 'en-GB', currency: 'GBP' }">Use £</button>
   <span x-money.decimal="price" data-locale=""localeObj></span>
 </div>
`

What do you think ?
Thanks for your time.

**Comment by markmead** [comment]
Ah OK, so something like this:

```html
<script>
window.xMoney = {
  locale: 'en-GB',
  currency: 'GBP'
}
</script>

<span x-money.global="productPrice"></span>
```

**Comment by billybillydev** [comment]
Big YES !!!

**Comment by markmead** [comment]
That's been added.
